name: Validate 'setup-xcode'
on:
  push:
    branches:
      - 'release/**'
  pull_request:
    branches:
      - 'release/**'

jobs:
  versions-macOS-14:
    name: macOS 14
    runs-on: macos-14
    strategy:
      matrix:
        xcode-version: ['15.4']
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: ./
      name: Setup Xcode
      id: setup-xcode
      with:
        xcode-version: ${{ matrix.xcode-version }}
    - name: Print output variables
      run: |
        echo "Version: ${{ steps.setup-xcode.outputs.version }}"
        echo "Path: ${{ steps.setup-xcode.outputs.path }}"
